"""empty message

Revision ID: 342da1c53559
Revises: 6b89679c75d9
Create Date: 2021-10-06 15:37:09.627562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342da1c53559'
down_revision = '6b89679c75d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_of_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_code', sa.String(length=255), nullable=True),
    sa.Column('detailed_discipline', sa.String(length=255), nullable=True),
    sa.Column('broad_dicsipline', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_of_education')
    # ### end Alembic commands ###
