"""Cluster fees

Revision ID: 6292eaf8d7a1
Revises: afdca1f03a14
Create Date: 2021-09-30 18:56:38.601085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6292eaf8d7a1'
down_revision = 'afdca1f03a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=255), nullable=True),
    sa.Column('cluster', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster')
    # ### end Alembic commands ###
