"""add total_fee

Revision ID: 9c0e6f31f0b8
Revises: eafef9286b94
Create Date: 2021-09-02 20:31:30.175384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0e6f31f0b8'
down_revision = 'eafef9286b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('international', sa.Column('total_fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('international', 'total_fee')
    # ### end Alembic commands ###
