"""empty message

Revision ID: 9efdf3098fc8
Revises: 
Create Date: 2021-10-18 12:20:58.161716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efdf3098fc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=255), nullable=True),
    sa.Column('cluster', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domestic_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_code', sa.String(length=255), nullable=True),
    sa.Column('course_title', sa.String(length=255), nullable=True),
    sa.Column('course_code', sa.String(length=255), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('yearly_points', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('fee_per_point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_of_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_code', sa.String(length=255), nullable=True),
    sa.Column('detailed_discipline', sa.String(length=255), nullable=True),
    sa.Column('broad_dicsipline', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('international',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=255), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('unit_set_code', sa.String(length=255), nullable=True),
    sa.Column('cricos', sa.String(length=255), nullable=True),
    sa.Column('course_title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=255), nullable=True),
    sa.Column('expiry_date', sa.String(length=255), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('yearly_points', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('total_fee', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('course_type', sa.String(length=255), nullable=True),
    sa.Column('course_owner', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_code', sa.String(length=255), nullable=True),
    sa.Column('unit_title', sa.String(length=255), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('credit_points', sa.Integer(), nullable=True),
    sa.Column('new_census_date', sa.String(length=255), nullable=True),
    sa.Column('dom_clust', sa.Integer(), nullable=True),
    sa.Column('non_clust', sa.Integer(), nullable=True),
    sa.Column('int_clust', sa.Integer(), nullable=True),
    sa.Column('foe', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    op.drop_table('international')
    op.drop_table('field_of_education')
    op.drop_table('domestic_post')
    op.drop_table('cluster')
    # ### end Alembic commands ###
