"""empty message

Revision ID: cf6764228e9f
Revises: 
Create Date: 2021-08-23 16:12:13.952591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6764228e9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_student', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('started', sa.String(length=255), nullable=True),
    sa.Column('expiry', sa.String(length=255), nullable=True),
    sa.Column('total_cp', sa.Integer(), nullable=True),
    sa.Column('yearly_cp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_student'], ['students.student_type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    op.drop_table('units')
    op.drop_table('students')
    # ### end Alembic commands ###
