"""empty message

Revision ID: eafef9286b94
Revises: 
Create Date: 2021-08-28 17:32:43.225514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafef9286b94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domestic_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_code', sa.String(length=255), nullable=True),
    sa.Column('course_title', sa.String(length=255), nullable=True),
    sa.Column('course_code', sa.String(length=255), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('yearly_points', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('fee_per_point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('international',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('unit_set_code', sa.String(length=255), nullable=True),
    sa.Column('cricos', sa.String(length=255), nullable=True),
    sa.Column('course_title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=255), nullable=True),
    sa.Column('expiry_date', sa.String(length=255), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('yearly_points', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('course_type', sa.String(length=255), nullable=True),
    sa.Column('course_owner', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('international')
    op.drop_table('domestic_post')
    # ### end Alembic commands ###
