name: Pa11y
on:
    push:
        branches: [main]
    pull_request:

jobs:
    pa11y:
        name: Pa11y
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: npm install, build react app
              run: |
                  cd ./client/
                  npm install && npm install -g pa11y
                  npm run build
            - name: Start server
              run: |
                  cd ./client/
                  http-server ./client/build/ -p 3000 -g & npx wait-on http://localhost:3000
            - name: Run pa11y
              run: |
                  cd ./client/
                  pa11y http://localhost:3000
